# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePermiso',
            fields=[
                ('id_detalle_permiso', models.IntegerField(db_column='ID_DETALLE_PERMISO', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Detalle de Permiso',
                'verbose_name_plural': 'Detalles de Permisos',
                'db_table': 'detalle_permiso',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PermisoUsuarioSucursal',
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'managed': False, 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False, 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='usuariosucursal',
            options={'managed': False, 'verbose_name': 'Usuario de Sucursal', 'verbose_name_plural': 'Usuarios de Sucursales'},
        ),
    ]
