# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id_detalle_producto', models.IntegerField(db_column='ID_DETALLE_PRODUCTO', primary_key=True, serialize=False)),
                ('precio_costo', models.DecimalField(db_column='PRECIO_COSTO', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'detalle_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(db_column='ID_MARCA', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='MARCA', max_length=35)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.CharField(db_column='COD_PRODUCTO', max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=35)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('porcentaje_ganancia', models.DecimalField(db_column='PORCENTAJE_GANANCIA', decimal_places=2, max_digits=4)),
                ('precio_venta', models.DecimalField(db_column='PRECIO_VENTA', decimal_places=2, max_digits=7)),
                ('fecha_agregado', models.DateField(db_column='FECHA_AGREGADO')),
                ('fecha_vencimiento', models.DateField(db_column='FECHA_VENCIMIENTO')),
                ('recien_ingreso', models.CharField(db_column='RECIEN_INGRESO', max_length=1)),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
