# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'managed': False, 'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalles de Productos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False, 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
