# Generated by Django 3.2.5 on 2021-10-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_auto_20211016_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
