# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('num_compra', models.IntegerField(db_column='NUM_COMPRA', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('total', models.DecimalField(db_column='TOTAL', decimal_places=2, max_digits=7)),
                ('total_pagado', models.DecimalField(db_column='TOTAL_PAGADO', decimal_places=2, max_digits=7)),
                ('pagado', models.CharField(db_column='PAGADO', max_length=1)),
                ('fecha_compra', models.DateField(db_column='FECHA_COMPRA')),
                ('entregado', models.CharField(db_column='ENTREGADO', max_length=1)),
                ('fecha_entregado', models.DateField(db_column='FECHA_ENTREGADO')),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.IntegerField(db_column='ID_DETALLE_COMPRA', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
                ('subtotal', models.DecimalField(db_column='SUBTOTAL', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
    ]
