# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('cod_descuento', models.CharField(db_column='COD_DESCUENTO', max_length=25, primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(db_column='PORCENTAJE', decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'descuento',
                'managed': False,
            },
        ),
    ]
