# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'managed': False, 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
    ]
