# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(db_column='ID_DEPARTAMENTO', primary_key=True, serialize=False)),
                ('departamento', models.CharField(blank=True, db_column='DEPARTAMENTO', max_length=25, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(db_column='ID_DIRECCION', primary_key=True, serialize=False)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=150)),
                ('referencia', models.CharField(blank=True, db_column='REFERENCIA', max_length=150, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(db_column='ID_MUNICIPIO', primary_key=True, serialize=False)),
                ('municipio', models.CharField(db_column='MUNICIPIO', max_length=35)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
    ]
