# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('num_cotizacion', models.IntegerField(db_column='NUM_COTIZACION', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(db_column='FECHA_VENTA')),
                ('total', models.DecimalField(db_column='TOTAL', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle_cotizacion', models.IntegerField(db_column='ID_DETALLE_COTIZACION', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
                ('subtotal', models.DecimalField(db_column='SUBTOTAL', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': False,
            },
        ),
    ]
