# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False, 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'managed': False, 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotizaciones'},
        ),
    ]
