# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nit_cliente', models.CharField(db_column='NIT_CLIENTE', max_length=15, primary_key=True, serialize=False)),
                ('mayorista', models.CharField(db_column='MAYORISTA', max_length=1)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('correo', models.CharField(db_column='CORREO', max_length=100, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='PASS', max_length=64)),
                ('activo', models.CharField(db_column='ACTIVO', max_length=1)),
                ('fecha_creado', models.DateField(blank=True, db_column='FECHA_CREADO', null=True)),
            ],
            options={
                'db_table': 'usuario_cliente',
                'managed': False,
            },
        ),
    ]
