# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
