# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.IntegerField(db_column='COD_EMPLEADO', primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='PASS', max_length=64)),
                ('correo', models.CharField(blank=True, db_column='CORREO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.IntegerField(db_column='ID_PUESTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('requisitos', models.CharField(blank=True, db_column='REQUISITOS', max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('salario', models.DecimalField(db_column='SALARIO', decimal_places=2, max_digits=7)),
                ('horario_entrada', models.TimeField(db_column='HORARIO_ENTRADA')),
                ('horario_salida', models.TimeField(db_column='HORARIO_SALIDA')),
            ],
            options={
                'db_table': 'puesto',
                'managed': False,
            },
        ),
    ]
