# Generated by Django 3.2.5 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefono',
            options={'managed': False, 'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
        migrations.AlterModelOptions(
            name='tipotelefono',
            options={'managed': False, 'verbose_name': 'Tipo de Teléfono', 'verbose_name_plural': 'Tipos de Teléfonos'},
        ),
    ]
